version: "3.9"

services:
  bot:
    build: .
    command: python -m bot.main
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  watcher:
    build: .
    command: python -m watcher.main
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app

  worker:
    build: .
    command: python -m queue.worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cellframe
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
